language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jbhatta1/docker_react -f Dockerfile.dev .

script:
  - docker run jbhatta1/docker_react npm run test -- --coverage