language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jbhatta/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true jbhatta/docker-react npm run test